name: Birthday Notify Every Day at 9 AM

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call birthdaysNotify endpoint and generate CallMeBot URL
        run: |
          echo "Obteniendo mensaje desde el endpoint..."
          RESPONSE=$(curl -s -X GET https://api-role-calendar.onrender.com/birthdaysNotify)
          echo "Respuesta cruda: $RESPONSE"

          # Extraer el campo message usando jq
          MESSAGE=$(echo "$RESPONSE" | jq -r '.message')
          echo "Mensaje procesado: $MESSAGE"

          # Usar secrets para CallMeBot
          TELEFONO="${{ secrets.CALLMEBOT_PHONE }}"
          APIKEY="${{ secrets.CALLMEBOT_APIKEY }}"

          # Generar URL y enviar WhatsApp
          URL="https://api.callmebot.com/whatsapp.php?phone=${TELEFONO}&text=${MESSAGE}&apikey=${APIKEY}"
          echo "Enviando WhatsApp..."
          curl -s "$URL"
          echo "Mensaje Enviado"
