- name: Call birthdaysNotify endpoint and generate CallMeBot URL
  run: |
    echo "Obteniendo mensaje desde el endpoint..."
    # Obtener el mensaje desde el endpoint
    MESSAGE=$(curl -s -X GET https://api-role-calendar.onrender.com/birthdaysNotify | jq -r '.message')

    # Definir teléfono y API key
    TELEFONO="5217714334090"
    APIKEY="9065110"

    # Convertir mensaje a URL safe
    ENCODED_MESSAGE=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$MESSAGE'''))")

    # Armar la URL con mensaje codificado
    URL="https://api.callmebot.com/whatsapp.php?phone=${TELEFONO}&text=${ENCODED_MESSAGE}&apikey=${APIKEY}"

    echo "URL generada:"
    echo "$URL"

    # Llamar la URL para enviar el WhatsApp
    curl -s "$URL"
