name: Birthday Notify Every Day at 9 AM

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call birthdaysNotify endpoint and generate CallMeBot URL
        run: |
          echo "Obteniendo mensaje desde el endpoint..."
          # Obtener el mensaje codificado desde el endpoint
          MESSAGE=$(curl -s -X GET https://api-role-calendar.onrender.com/birthdaysNotify | jq -r '.message')

          # Usar secrets en vez de hardcode
          TELEFONO="${{ secrets.CALLMEBOT_PHONE }}"
          APIKEY="${{ secrets.CALLMEBOT_APIKEY }}"

          URL="https://api.callmebot.com/whatsapp.php?phone=${TELEFONO}&text=${MESSAGE}&apikey=${APIKEY}"

          echo "Enviando WhatsApp..."
          curl -s "$URL"
