name: Birthday Notify Every Day at 9 AM

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call birthdaysNotify endpoint and generate CallMeBot URL
        run: |
          echo "Obteniendo mensaje desde el endpoint..."
          RESPONSE=$(curl -s -X GET https://api-role-calendar.onrender.com/birthdaysNotify)
          echo "Respuesta cruda: $RESPONSE"

          # Extraer message
          MESSAGE=$(echo "$RESPONSE" | jq -r '.message')
          echo "Mensaje crudo: $MESSAGE"

          # Codificar URL correctamente
          MESSAGE_ENCODED=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$MESSAGE")
          echo "Mensaje codificado: $MESSAGE_ENCODED"

          TELEFONO="${{ secrets.CALLMEBOT_PHONE }}"
          APIKEY="${{ secrets.CALLMEBOT_APIKEY }}"

          URL="https://api.callmebot.com/whatsapp.php?phone=${TELEFONO}&text=${MESSAGE_ENCODED}&apikey=${APIKEY}"
          echo "Enviando WhatsApp..."
          curl -s "$URL"
