name: Birthday Notify Every 5 Minutes

# Se ejecuta cada 5 minutos
on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:       # Permite ejecutarlo manualmente también

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call birthdaysNotify endpoint
        run: |
          curl -X GET https://api-role-calendar.onrender.com/birthdaysNotify
